version: '3.4'

services:
  mars.web:
    container_name: marsweb
    image: ${DOCKER_REGISTRY-}marsweb
    build:
      context: .
      dockerfile: Mars.Web/Dockerfile
    environment:
      - SeqServer=http://seq

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "8888:80"
    volumes:
      - /datadrive:/data
    environment:
      - ACCEPT_EULA=Y

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - jaegernet
    depends_on:
      - mars.web

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/
      - prom_data:/prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./grafana:/var/lib/grafana

  loki:
    container_name: loki
    image: grafana/loki:master
    ports:
       - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
       - ./loki:/etc/loki

volumes:
  prom_data:

networks:
  jaegernet: